name: Test Workload

on:
  workflow_call:
    inputs:
      cluster-name:
        required: true
        description: AKS Cluster Name
        type: string

jobs:
  test-workload:
    name: Test Workload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
            
      - name: Install Dependencies 
        id: install-dependencies 
        run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" --fail-with-body 
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin
            kubectl version 2>&1 || true

      - name: Test Workload
        env:
          CLUSTER_NAME: ${{ inputs.cluster-name }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }} 
        id: test-workload
        run: | 
          az aks get-credentials --name $CLUSTER_NAME  --resource-group $RESOURCE_GROUP  --overwrite-existing

          echo "Wait for 120 sec before checking expected Kafka message."
          sleep 120

          max_retries=5
          retries=0
          while [ $retries -lt $max_retries ]; do
              echo "Querying for the decrypted message from $ConsumerIP"
              result=$(kubectl logs -n kafka kafka-golang-consumer -c kafka-golang-consumer) 

              if [[ $result == *"Azure Confidential Computing"* ]]; then
                  echo "Returned result is $result"
                  echo "Found decrypted message, workload is successful."
                  break  # Exit the loop on successful attempt
              else
                  echo "Returned result is $result"
                  echo "Returned result does not contain text that indicates successful execution, retrying in 5 seconds..."
                  retries=$((retries+1))
              fi
              sleep 5
          done

          if [ $retries -eq $max_retries ]; then
            echo "The operation has been tried 3 times without success."
            exit 1
          fi